title: "Jennifer Saldana"
author: "Jennifer Saldana"
description: "Louisiana State University A&M"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter, if its false you dont need to change icon

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "about.md", title: /about, sidebaricon: address-card}
  - {file: "blog.md", title: /blog, sidebaricon: address-card}
  - {url: "JenniferMarieSaldana_s_Resume.pdf", title: /CV, sidebaricon: home}
  
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:jenni.sald04@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Jennifersaldana"}
  - {title: Credly, icon: rss, url: "https://www.credly.com/users/jennifermariesaldana"}
  - {title: Linkedin, icon: rss, url: "https://www.linkedin.com/in/jennifermariesaldana/"} 

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
